### ISSUE TITLE
Add breadcrumb arrow sizes

### ISSUE THREAD

**Issue by develop67** [tarkhov/postboot#192]
```css
.breadcrumb-rsaquo .breadcrumb-item+.breadcrumb-item::before {
    content: "\203A";
    font-size: 1.3rem;
    line-height: 1.1;
}
```
