### ISSUE TITLE
Add .col-2-5 for 5 columns grid

### ISSUE THREAD

**Issue by develop67** [tarkhov/postboot#56]
https://getbootstrap.com/docs/4.3/layout/grid/#example-usage
```scss
@each $breakpoint in map-keys($grid-breakpoints) {
  $infix: breakpoint-infix($breakpoint);

  .col#{$infix}-2-5 {
    @include make-col-ready();
  }

  @include media-breakpoint-up($breakpoint) {
    .col#{$infix}-2-5 {
      @include make-col(2.4);
    }
  }
}
```
