### ISSUE TITLE
Add .flex-center utility

### ISSUE THREAD

**Issue by develop67** [tarkhov/postboot#58]
Wich contains:
```scss
.flex-center {
  display: flex;
  justify-content: center;
  align-items: center;
}

.flex-x-center {
  display: flex;
  justify-content: center;
}

.flex-y-center {
  display: flex;
  align-items: center;
}
```
And responsive alternatives like `.flex-sm-center`, `.flex-sm-x-center`.
