### ISSUE TITLE
More flex utilities

### ISSUE THREAD

**Issue by develop67** [tarkhov/postboot#79]
```scss
.flex-left {
  display: flex !important;
  justify-content: flex-start !important;
}
.flex-right {
  display: flex !important;
  justify-content: flex-end !important;
}
.flex-between {
  display: flex !important;
  justify-content: space-between !important;
}
.flex-around {
  display: flex !important;
  justify-content: space-around !important;
}
.flex-top {
  display: flex !important;
  align-items: flex-start !important;
}
.flex-bottom {
  display: flex !important;
  align-items: flex-end !important;
}
.flex-baseline {
  display: flex !important;
  align-items: baseline !important;
}
.flex-stretch {
  display: flex !important;
  align-items: stretch !important;
}

// Align
.flex-align-between {
  display: flex !important;
  flex-wrap: wrap !important;
  align-content: space-between !important;
}
.flex-align-around {
  display: flex !important;
  flex-wrap: wrap !important;
  align-content: space-around !important;
}
.flex-align-top {
  display: flex !important;
  flex-wrap: wrap !important;
  align-content: flex-start !important;
}
.flex-align-bottom {
  display: flex !important;
  flex-wrap: wrap !important;
  align-content: flex-end !important;
}
.flex-align-center {
  display: flex !important;
  flex-wrap: wrap !important;
  align-content: center !important;
}
.flex-align-stretch {
  display: flex !important;
  flex-wrap: wrap !important;
  align-content: stretch !important;
}
```
