### ISSUE TITLE
Add .sidebar-modal-right

### ISSUE THREAD

**Issue by tarkhov** [tarkhov/postboot#87]
Replace `.sidebar-dialog` **max-width** to **width**.
```scss
.sidebar-modal-right {
  .sidebar-dialog {
    width: 250px;
    float: right;   
  }
  
  &.fade {
     transform: translate(50px,0);
  }

  .modal-open & {
    padding-right: 0 !important;
  }
}
```
